### PR TITLE
Disable incremental tasks api for format task.

### LINKED ISSUE #302: Running ktlintFormat twice deletes files
**Steps to reproduce the bug**
1) Use ktlint-gradle version `9.1.0` and ktlint version `0.35.0` with the following configuration:
```
ktlint {
    version = "0.35.0"
    debug = true
    verbose = true
    android = true
    outputToConsole = true
    outputColorName = "RED"
    enableExperimentalRules = false
}
```
2) Run `./gradlew ktlintFormat --continue` once. (Then run `git status`, and observe that the auto-formatted files were modified)
3) Run `./gradlew ktlintFormat --continue` a second time

**Expected Behavior**
Running `./gradlew ktlintFormat --continue` the second time should not making any additional changes. The previously modified files should still show up as modified in `git status`, and no files should be deleted.

**Actual Behavior**
All the files that were previously marked as modified are now `deleted` (observed via `git status`).

I also tried the gradle integration recommended in https://github.com/pinterest/ktlint without plugins, and running the non-plugin `ktlintFormat` task multiple times did not delete any files. This makes me suspect that the bug is in `ktlint-gradle`.

### PR DESCRIPTION
**Pull request by Tapchicoma**
Disabled incremental task api for format task. As format task declares output same as input and incremental api deletes all outputs on inputs changes, this lead to files deletion on the second run.

Fixes #302

### CODE REVIEW

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt [hunk 1]
```diff
@@ -1,14 +1,38 @@
...
+            .fold(mutableSetOf<File>()) { acc, fileChange ->
+                logger.debug("File changed: $fileChange")
+                with(fileChange) {
+                    if (fileType != FileType.DIRECTORY &&
+                        changeType != ChangeType.REMOVED) {
+                        acc.add(file)
+                    }
+                }
+                acc
+            }
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt]: You could also do `map` with a `filterNonNull` afterward. This works too though.

File: plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt [hunk 2]
```diff
@@ -157,14 +157,15 @@ abstract class BaseKtlintPluginTest : AbstractPluginTest() {
...
+            assertThat(task(":ktlintMainSourceSetFormat")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
         }
 
         projectRoot.restoreFailingSources()
 
         build(":ktlintFormat").apply {
-            assertThat(task(":ktlintMainSourceSetFormat")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
+            assertThat(task(":ktlintMainSourceSetFormat")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
         }
+        assertThat(projectRoot.resolve(FAIL_SOURCE_FILE)).exists()
```
Comment (Tapchicoma) [inline plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt]: @JLLeitschuh the test is here :)

Comment (JLLeitschuh) [reply plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt]: Cool! Awesome!

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt (hunk 1 above)
Comment (Tapchicoma) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt]: Force updated this part.
