### PR TITLE
Fix .editorconfig file change doesn't reset check task state.

### LINKED ISSUE #106: Editorconfig file should be treated as input
Currently check task caching doesn't take into consideration any changes in `.editorconfig` file. 

For example, if I add `max_line_length=40` to `.editorconfig`, task result will still be taken from Gradle cache.

### PR DESCRIPTION
**Pull request by Tapchicoma**
This PR fixes issue that `ktlintCheck` task ignores `.editorconfig` file changes.

For now task assumes that `.editorconfig` file will be either in root project folder or in current project folder. If somebody will need more advanced logic - new issue should be created and this problem will be addressed in a separate PR.

Fixes #106.

### CODE REVIEW

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt [hunk 1]
```diff
@@ -43,6 +46,11 @@ open class KtlintCheck @Inject constructor(objectFactory: ObjectFactory) : Defau
         }
     }
 
+    @get:SkipWhenEmpty
+    @get:PathSensitive(PathSensitivity.RELATIVE)
+    @get:InputFiles
+    val editorConfigFiles: FileCollection = project.rootProject.files(EDITORCONGIG_FILE_NAME)
+        .plus(project.files(EDITORCONGIG_FILE_NAME))
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt]: Do you want to use a `RegularFileProperty` instead? Then you can annotate it as `@get:InputFile` instead of `@get:InputFiles`. Unless you think the user can specify multiple files.

Also, do you want to consider making this field `internal` or do you want to allow users to modify it?

**Comment by JLLeitschuh** [comment]
Thanks for working on fixing this!

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt (hunk 1 above)
Comment (JLLeitschuh) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt]: Totally makes sense.

Another problem with the way you have this is that the root project is not always necessarily in a parent directory.
It is completely valid to have a structure like this:
```
someDir
 - rootProject
   - rootProject.gradle
   - .editorconfig
   - settings.gradle
 - subprojects
   - subprojects.gradle
   - .editorconfig
     - subprojectA
       - subprjoectA.gradle
       - .editorconfig
```
I understand this is an atypical project structure. But it is completely valid.

See the "Where are these files stored?" section from this document to see how the filesystem walking should really happen:
https://editorconfig.org/

Comment (Tapchicoma) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt]: Ok, I will try to adapt proposed strategy for detecting `.editorconfig` files that is seems to be similar how it is in the Ktlint :+1:

**Comment by Tapchicoma** [comment]
@JLLeitschuh reworked how `.editorconfig` files are detected - it uses similar algorithm as KtLint.

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt [hunk 2]
```diff
@@ -43,6 +44,10 @@ open class KtlintCheck @Inject constructor(objectFactory: ObjectFactory) : Defau
         }
     }
 
+    @get:SkipWhenEmpty
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt]: Uhhhh. I don't think we want to skip the task when there isn't a `.editorconfig` file.

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt [hunk 3]
```diff
@@ -43,6 +44,10 @@ open class KtlintCheck @Inject constructor(objectFactory: ObjectFactory) : Defau
...
+    @get:PathSensitive(PathSensitivity.RELATIVE)
+    @get:InputFiles
+    internal val editorConfigFiles: FileCollection = getEditorConfigFiles(project)
     @get:Input
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt]: Can you add a newline here above this line.

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt [hunk 4]
```diff
@@ -22,6 +24,56 @@ internal inline fun <reified T : Task> Project.taskHelper(name: String, noinline
...
+    return if (parentDir != null &&
+        parentDir != project.rootDir.toPath() &&
+        !editorConfigFC.isRootEditorConfig()) {
+        searchEditorConfigFiles(project, parentDir, outputCollection)
+    } else {
+        outputCollection
+    }
+}
+
+private val editorConfigRootRegex = "^root\\s?=\\s?true\\n".toRegex()
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt]: Thank you for caching this so it only needs to be compiled once! 👍

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt (hunk 2 above)
Comment (Tapchicoma) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt]: :scream: Thank you for pointing this out!

**Comment by Tapchicoma** [comment]
@JLLeitschuh fixed comments
