### PR TITLE
Pass arguments to ktlint as file input.

### LINKED ISSUE #233: Fails to run ktlint on over 3000 kotlin files in sourceset
Plugin fails to run check/format tasks, when source set contains over 3000 kotlin files.

Currently plugin passes each file to `ktlint` and in this case may hit command line arguments limitation. (at least on Windows or MacOS).

Opened after discussion in #156

### PR DESCRIPTION
**Pull request by Tapchicoma**
Ktlint starts using https://picocli.info/#AtFiles command line option, that
allows to pass arguments to command line invocation from file.
Such approach should solve maximum command line arguments limitation.

Don't need to bump minimum support ktlint version here as picoli dependency on ktlint project was introduced more then 2 years ago, before minimum supported version was released.

Sample of such "args" file for `:samples:kotlin-ks` project:
```
       │ File: samples/kotlin-ks/build/ktlint/ktlintMainSourceSetCheck.args
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ --verbose
   2   │ --reporter=plain
   3   │ --color
   4   │ --reporter=checkstyle,output=/home/egorr/data/work/ktlint-gradle/samples/kotlin-ks/build/reports/ktlint/ktlintMainSourceSetCheck.xml
   5   │ --reporter=json,output=/home/egorr/data/work/ktlint-gradle/samples/kotlin-ks/build/reports/ktlint/ktlintMainSourceSetCheck.json
   6   │ src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/kotlin/main.kt
``` 

Closes #233

### CODE REVIEW

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt [hunk 1]
```diff
@@ -104,39 +105,54 @@ abstract class BaseKtlintCheckTask(
...
+    @OutputFiles
+    private fun ktlintArgsFile() = newFileProperty(objectFactory, projectLayout).apply {
+        set(
+            project.layout.buildDirectory.file(
+                project.provider {
+                    "ktlint/${this@BaseKtlintCheckTask.name}.args"
+                }
+            )
+        )
+    }
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt]: Shouldn't this be a lazy prop instead of a method? Currently every time you execute this method, a new property will be generated.

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt [hunk 2]
```diff
@@ -104,39 +105,54 @@ abstract class BaseKtlintCheckTask(
...
+            .map { "--ruleset=${it.absolutePath}" }
+            .forEach { argsWriter.println(it) }
+        enabledReports
+            .map { it.asArgument() }
+            .forEach { argsWriter.println(it) }
+        getSource()
+            .toRelativeFilesList()
+            .forEach { argsWriter.println(it) }
+        additionalConfig(argsWriter)
+        argsWriter.close()
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt]: Shouldn't this be in a `use` block so that if any of the above fail, we don't end up leaving a dangling file descriptor?

**Comment by Tapchicoma** [comment]
@JLLeitschuh addressed review comments

File: CHANGELOG.md [hunk 3]
```diff
@@ -16,7 +16,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/).
   - Support for "kotlin-native-gradle-plugin" plugin
   - Deprecated `ruleset` extension property, please use `ruleset` configuration instead
 ### Fixed
-  - ?
+  - Task may fail on command line arguments limit (#233)
```
Comment (JLLeitschuh) [inline CHANGELOG.md]:
```suggestion
  - Task failing when command line arguments limit was reached (#233)
```

**Comment by tprochazka** [comment]
It needs some change in setup to enable it? 
My project just started to crash during the source code check.
So I tried to update to 9.0.0 and it doesn't help :-(

```
* What went wrong:
Execution failed for task ':app:ktlintMainSourceSetCheck'.
> Process 'command 'C:\PJazyky\_IDE\android-studio-3.5.X\jre\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:ktlintMainSourceSetCheck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\PJazyky\_IDE\android-studio-3.5.X\jre\bin\java.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:409)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:40)
        at org.gradle.process.internal.DefaultExecActionFactory.javaexec(DefaultExecActionFactory.java:138)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1107)
        at org.jlleitschuh.gradle.ktlint.BaseKtlintCheckTask.lint(BaseKtlintCheckTask.kt:140)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.executeAndStoreInCache(CacheStep.java:187)
        at org.gradle.internal.execution.steps.CacheStep.lambda$executeWithCache$2(CacheStep.java:110)
        at org.gradle.internal.execution.steps.CacheStep.lambda$executeWithCache$3(CacheStep.java:110)
        at org.gradle.internal.Try$1.apply(Try.java:59)
        at org.gradle.internal.Try$1.apply(Try.java:56)
        at org.gradle.internal.Try$Success.flatMap(Try.java:102)
        at org.gradle.internal.Try.map(Try.java:56)
        at org.gradle.internal.execution.steps.CacheStep.executeWithCache(CacheStep.java:79)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:69)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        ... 35 more
```

**Comment by Tapchicoma** [comment]
> It needs some change in setup to enable it?
> My project just started to crash during the source code check.
> So I tried to update to 9.0.0 and it doesn't help :-(

No, it does not require any configuration change beside plugin version update to `9.0.0`. From the crashlog above, imho, failed state is related to the default ktlint version update, rather then from this feature implementation.

@tprochazka could you enable debug for ktlint (`ktlint.debug = true`) and check output?

**Comment by tprochazka** [comment]
Sorry for delay. 
But it is Weird. it looks that it crash at the end:

`...my-cleaner\app\src\main\java\com\my\android\cleanercore\internal\entity\CloudItem.kt:1:1: File must end with a newline (\n)
...my-cleaner\app\src\main\java\com\my\android\cleanercore\internal\entity\IgnoredItem.kt:1:1: File must end with a newline (\n)
...my-cleaner\app\src\main\java\com\my\android\cleanercore\internal\entity\TransferredItem.kt:1:1: File must end with a newline (\n)
[DEBUG] Discovered .editorconfig (...my-cleaner) {max_line_length=off}
...my-cleaner\app\src\main\java\com\my\android\cleanercore\internal\entity\UsageStats.kt:1:1: File must end with a newline (\n)
...my-cleaner\app\src\main\java\com\my\android\cleanercore\internal\ScannerFlagHelper.kt:1:1: File must end with a newline (\n)
[DEBUG] Checking ...my-cleaner\app\src\main\java\com\my\android\cleanercore\scanner\service\CleaningAndroidService.kt
[DEBUG] Discovered .editorconfig (...my-cleaner) {max_line_length=off}
...my-cleaner\app\src\main\java\com\my\android\cleanercore\scanner\service\CleaningAndroidService.kt:3:1: Imports must be ordered in lexicographic order without any empty lines in-between
[DEBUG] Checking ...my-cleaner\app\src\main\java\com\my\android\cleanercore\usagestats\UsageStatsDb.kt
[DEBUG] Checking ...my-cleaner\app\src\main\java\com\my\android\cleanercore\usagestats\UsageStatsService.kt
[DEBUG] Discovered .editorconfig (...my-cleaner) {max_line_length=off}
[DEBUG] Discovered .editorconfig (...my-cleaner) {max_line_length=off}
...my-cleaner\app\src\main\java\com\my\android\cleanercore\usagestats\UsageStatsDb.kt:14:1: Imports must be ordered in lexicographic order without any empty lines in-between
...my-cleaner\app\src\main\java\com\my\android\cleanercore\usagestats\UsageStatsService.kt:14:1: Imports must be ordered in lexicographic order without any empty lines in-between
"plain" report written to ...my-cleaner\app\build\reports\ktlint\ktlintMainSourceSetCheck.txt
[DEBUG] 13303ms / 325 file(s) / 264 error(s)

> Task :app:ktlintMainSourceSetCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:ktlintMainSourceSetCheck'.
> Process 'command 'C:\PJazyky\_IDE\android-studio-3.6.X\jre\bin\java.exe'' finished with non-zero exit value 1
`

**Comment by Tapchicoma** [comment]
@tprochazka it is not related to this issue, your kotlin files violates some ktlint style rules.
