### PR TITLE
Rethink format task approach

### LINKED ISSUE #306: Rethink format task approach
Currently format tasks works the same as common lint tasks, except that they may modify inputs. This leads to the several problems with this tasks caching: #302 or #194 

Possible solutions to this problem:
- actually run lint tasks first, don't fail the tasks, then run format only on files with files violations. Format task is never cacheable, but uses lint tasks reports as input.
- something else?

@JLLeitschuh maybe something else comes to your mind how to solve it as well?

### LINKED ISSUE #423: ktlintFormat creates directories under src
When I run `ktlintFormat` there are the following directories, which are created under `src` directory:
- src/main/java
- src/main/kotlin
- src/test/java
- src/test/kotlin

It is pretty annoying seeing java directory all the time and have no chance to get rid of it when you write a 100% Kotlin project. Is there a way to ask ktlint not to create these directories?

### PR DESCRIPTION
**Pull request by Tapchicoma**
`BaseKtlintCheckTask` now extends `DefaultTask` plus implements `PatternFilterable` interface copying approach from `SourceTask`.

To better handle incremental formatting, plus handle the case of restored to pre-formatted state sources, Format task tracks pre-formatted files snapshot: file + content hash. In case sources has the files with same content hash as file in snapshot from previous task execution - format tasks fails up-to-date check and run format again on such files.

Fixes #423
Fixes #306

### CODE REVIEW

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt [hunk 1]
```diff
@@ -87,6 +92,9 @@ abstract class BaseKtLintCheckTask @Inject constructor(
         convention("256m")
     }
 
+    private var sourceFiles: ConfigurableFileCollection = objectFactory.fileCollection()
+    private val patternSet: PatternFilterable = PatternSet()
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt:96]: Can an instance be injected? I don't think the constructor will be change, but if it is, this way we're forwards compatible.

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,9 +13,11 @@ and this project adheres to [Semantic Versioning](https://semver.org/).
   - Update Gradle to `7.1.1` version
   - Update Shadow plugin to `7.0.0` version
   - Update Kotlin to `1.5.21` version
+  - Rethink format task approach ([issue: $306](https://github.com/JLLeitschuh/ktlint-gradle/issues/306))
 
 ### Fixed
   - Pre-commit hook causing conflicts ([issue: #443](https://github.com/JLLeitschuh/ktlint-gradle/issues/443)) ([#502](https://github.com/JLLeitschuh/ktlint-gradle/pull/502))
+  - `ktlintFormat` create empty directories in `src/` dir ([issue: $423](https://github.com/JLLeitschuh/ktlint-gradle/issues/423))
```
Comment (JLLeitschuh) [inline CHANGELOG.md:20]: Is this syntax correct? Shouldn't it be this?
```suggestion
  - `ktlintFormat` create empty directories in `src/` dir ([issue: #423](https://github.com/JLLeitschuh/ktlint-gradle/issues/423))
```
Same question about the line above

**Review by JLLeitschuh — CHANGES_REQUESTED** [review]
Looks good to me other than the issue in the changelog

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt (hunk 1 above)
Comment (Tapchicoma) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt]: Unfortunately `PatternFilterable` is not injectable by Gradle, so I changed the code to pass `PatternSet` as a constructor parameter.

File: CHANGELOG.md (hunk 2 above)
Comment (Tapchicoma) [reply CHANGELOG.md]: Fixed the typo!

**Comment by Tapchicoma** [comment]
@JLLeitschuh could you check updated PR?

**Review by JLLeitschuh — APPROVED** [review]
LGTM!
