### PR TITLE
Fix configuration cache for relative paths

### LINKED ISSUE #721: Configuration cache broken with relative set to true
Hello there.

When we set `relative.set(true)` our configuration cache breaks with something along the line of
```
855 problems were found storing the configuration cache, 285 of which seem unique.
- Task `:app:ktlintBenchmarkSourceSetFormat` of type `org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask`: invocation of 'Task.project' at execution time is unsupported.
```

This is probably because
https://github.com/JLLeitschuh/ktlint-gradle/blob/431af6b838915abc874c63e92955c9272c5d08dd/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt#L144-L146
is using project directly.

According to the table on https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements project.rootDir should be replaced with `A task input or output property or a script variable to capture the result of using project.rootDir to calculate the actual parameter.`

Thanks in advance!

### PR DESCRIPTION
**Pull request by rschattauer**
resolves #721 

The new test would fail before the changes to generate reports task and succeed afterwards

### CODE REVIEW

File: plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt [hunk 1]
```diff
@@ -58,15 +59,13 @@ class ConfigurationCacheTest : AbstractPluginTest() {
             val formatTaskName = KtLintFormatTask.buildTaskNameForSourceSet("main")
             build(
                 configurationCacheFlag,
-                configurationCacheWarnFlag,
```
Comment (JLLeitschuh) [inline plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt:61]: Can you elaborate on why this isn't needed anymore?

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt [hunk 2]
```diff
@@ -90,6 +90,8 @@ abstract class GenerateReportsTask @Inject constructor(
     @get:Optional
     internal abstract val baseline: RegularFileProperty
 
+    private val rootDir: File = project.rootDir
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt:93]: Does this need to be class scoped? Or can it be scoped smaller, to only the `init` block? Also, can you elaborate on why this fixes this, or, at minimum, can you include an explicit comment in the code explaining why this is extracted to a variable eagerly. That way the rationale for this change isn't lost in the future? 🙂

**Review by JLLeitschuh — COMMENTED** [review]
Just a few bits of feedback and some questions. Other than that, nice work!

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt (hunk 2 above)
Comment (rschattauer) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt:98]: According to https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:~:text=Use%3A-,project.rootDir,-A%20task%20input for configuration caching rootDir you should use
`A task input or output property or a script variable to capture the result of using project.rootDir to calculate the actual parameter.`
So according to https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution `A task must not use any Project objects at execution time. This includes calling Task.getProject() while the task is running.` and to achieve that I was calling it within the class. I could also let the input set the relative rootdir path, but I thought this is easier to grasp? I added a comment to hopefully make it understandable.

What do you mean with init block scoped? There is no difference to this and 
```
private val rootDir: File
init {
     rootDir = project.rootDir
}
``
`
or do I misunderstand you?

File: plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt (hunk 1 above)
Comment (rschattauer) [reply plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt:61]: I removed it everywhere in this test now. Reason being that this would not fail the test when configuration actually fails. With relative path you would get a message that reads something like
```
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

2 problems were found storing the configuration cache, 1 of which seems unique.
```
So we probably want this test to fail in the future if someone implements something that is not capable of configuration caching?

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt (hunk 2 above)
Comment (JLLeitschuh) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt:98]: Sorry, I misunderstood the code. I thought the `rootDir` was only used inside of the `init` block, but re-reading the code, I was completely wrong. My mistake.

Thanks for adding a comment inline in the code! 🙂

**Review by JLLeitschuh — APPROVED** [review]
LGTM!

**Comment by JLLeitschuh** [comment]
Please add a changelog entry for this change. Then this should be good to go

**Comment by rschattauer** [comment]
Added a line to the changelog @JLLeitschuh

**Review by JLLeitschuh — APPROVED** [review]
LGTM! Now to wait for CI

**Comment by rschattauer** [comment]
@JLLeitschuh , I don't have to click/do anything to continue, correct?

**Comment by JLLeitschuh** [comment]
Merged! Thanks for the fix!!
