### PR TITLE
Fix wrong up-to-date state of format task.

### LINKED ISSUE #194: ktlintFormat is up-to-date when it shouldn't be
To reproduce:
1. Do a small change that would be fixed by ktlint (e.g. inserting a space before a `,`) 
2. Run `gw ktlintFormat` 
3. The change should be undone now
4. Do the same change you did in 1 again
5. Run `gw ktlintFormat` again
-> The task will be up-to-date and the change still be there

### PR DESCRIPTION
**Pull request by Tapchicoma**
Fixes #194: Format task may produce up-to-date state, if sources was restored to pre-format state, so task input considered to be cached from success run.

Current solution is not perfect, but, currently, there are no better ways in Gradle:
- on first run format changes the sources and produce stable output content 
- on second run gradle produces stable input content with the same output
- on third run task is considered "UP-TO-DATE" and cached

### CODE REVIEW

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt [hunk 1]
```diff
@@ -1,13 +1,31 @@
...
     override fun additionalConfig(): (JavaExecSpec) -> Unit = {
         it.args("-F")
     }
+
+    /**
+     * Fixes the issue when input file is restored to pre-format state and running format task again fails
+     * with "up-to-date" task state.
+     *
+     * Note this approach sets task to "up-to-date" only on 3rd run when both input and output sources are the same.
+     */
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt]: @nedtwigg I know you fixed this same problem with Spotless. Care to offer any insights into how you resolved it?

Comment (nedtwigg) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt]: I wrote it up [here](https://discuss.gradle.org/t/two-cases-where-the-incremental-api-is-lacking/24266), and included links to the PR's that fixed it.

Comment (Tapchicoma) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt]: It is kind of complex solution, I'd prefer not introduce it here.
