### PR TITLE
Fix running check task triggers execution of some android tasks.

### LINKED ISSUE #63: ktlintFormat and ktlintCheck also run compilation related tasks
At the very least, this issue pertains to Android projects. I recall a previous version of this plugin running much faster as I believe all it did was simply invoke `ktlint`. The more recent versions seem to do a lot more than just run `ktlint`. This plugin now seems to build your app before running `ktlint`. Not sure if this is by design.

Please see logs below. Both tasks were run after running `./gradlew clean`. The project I tested this with was a barebones sample Android project.

**ktlintFormat**
```
./gradlew ktlintFormat --console=plain
:app:preBuild UP-TO-DATE
:app:preDebugAndroidTestBuild
:app:compileDebugAndroidTestAidl
:app:preDebugBuild
:app:checkDebugManifest
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:processDebugAndroidTestManifest
:app:compileDebugAndroidTestRenderscript
:app:generateDebugAndroidTestBuildConfig
:app:generateDebugAndroidTestResValues
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:splitsDiscoveryTaskDebugAndroidTest
:app:processDebugAndroidTestResources
:app:ktlintDebugAndroidTestFormat
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:splitsDiscoveryTaskDebug
:app:processDebugResources
:app:ktlintDebugFormat
:app:ktlintDebugUnitTestFormat
:app:preReleaseBuild
:app:compileReleaseAidl
:app:compileReleaseRenderscript
:app:checkReleaseManifest
:app:generateReleaseBuildConfig
:app:generateReleaseResValues
:app:generateReleaseResources
:app:mergeReleaseResources
:app:createReleaseCompatibleScreenManifests
:app:processReleaseManifest
:app:splitsDiscoveryTaskRelease
:app:processReleaseResources
:app:ktlintReleaseFormat
:app:ktlintReleaseUnitTestFormat
:ktlintFormat
:app:ktlintFormat

BUILD SUCCESSFUL in 5s
36 actionable tasks: 36 executed
```

**ktlintCheck**
```
./gradlew ktlintCheck --console=plain
:app:preBuild UP-TO-DATE
:app:preDebugAndroidTestBuild
:app:compileDebugAndroidTestAidl
:app:preDebugBuild
:app:checkDebugManifest
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:processDebugAndroidTestManifest
:app:compileDebugAndroidTestRenderscript
:app:generateDebugAndroidTestBuildConfig
:app:generateDebugAndroidTestResValues
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:splitsDiscoveryTaskDebugAndroidTest
:app:processDebugAndroidTestResources
:app:ktlintDebugAndroidTestCheck
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:splitsDiscoveryTaskDebug
:app:processDebugResources
:app:ktlintDebugCheck
:app:ktlintDebugUnitTestCheck
:app:preReleaseBuild
:app:compileReleaseAidl
:app:compileReleaseRenderscript
:app:checkReleaseManifest
:app:generateReleaseBuildConfig
:app:generateReleaseResValues
:app:generateReleaseResources
:app:mergeReleaseResources
:app:createReleaseCompatibleScreenManifests
:app:processReleaseManifest
:app:splitsDiscoveryTaskRelease
:app:processReleaseResources
:app:ktlintReleaseCheck
:app:ktlintReleaseUnitTestCheck
:ktlintCheck
:app:ktlintCheck

BUILD SUCCESSFUL in 6s
36 actionable tasks: 36 executed
```

### PR DESCRIPTION
**Pull request by Tapchicoma**
Fixes #63.

Now running `ktlintCheck` tasks doesn't trigger some android tasks execution:
```
$ ./gradlew -m :samples:android-app:ktlintCheck
:samples:android-app:ktlintDebugAndroidTestCheck SKIPPED
:samples:android-app:ktlintDebugCheck SKIPPED
:samples:android-app:ktlintDebugUnitTestCheck SKIPPED
:samples:android-app:ktlintReleaseCheck SKIPPED
:samples:android-app:ktlintReleaseUnitTestCheck SKIPPED
:samples:android-app:ktlintCheck SKIPPED

BUILD SUCCESSFUL in 1s
```

### CODE REVIEW

File: plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt [hunk 1]
```diff
@@ -99,7 +100,13 @@ open class KtlintPlugin : Plugin<Project> {
                 }
 
                 variantManager?.variantScopes?.forEach {
-                    val kotlinSourceDir = target.files(it.variantData.javaSources)
+                    val sourceDirs = it.variantData.javaSources
+                            .fold(mutableListOf<File>()) { acc, configurableFileTree ->
+                                acc.add(configurableFileTree.dir)
+                                acc
```
Comment (JLLeitschuh) [inline plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt]: Could be replaced with `acc += configurableFileTree.dir` right?

Comment (Tapchicoma) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt]: Actually no, because `plusAssign` fun returns `Unit`, so additional `acc` still required.

Comment (JLLeitschuh) [reply plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt]: Fair enough.
